import React, { useMemo } from 'react';
import { useFilter } from '../context/FilterContext';
import {
    BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, Legend
} from 'recharts';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';

export const ActivityAnalysis: React.FC = () => {
    const { filteredSales } = useFilter();

    // 1. Daily Activity Evolution
    const evolutionData = useMemo(() => {
        const grouped: Record<string, { date: string, calls: number, whats: number }> = {};

        filteredSales.forEach(s => {
            // Ideally use "Activity Date" but we only have Registration/Won Date.
            // Proxy: Use Registration Date to approximate when "First Contact" happened.
            if (s.registrationDate) {
                const dateKey = format(s.registrationDate, 'yyyy-MM-dd');
                if (!grouped[dateKey]) grouped[dateKey] = { date: dateKey, calls: 0, whats: 0 };
                // Aggregate TOTAL calls for that lead on that day? 
                // No, the CSV has "Total Calls" per lead. We don't know WHEN they happened.
                // WEAKNESS: We can't plot daily activity accurately without an Activity Log.
                // Workaround: Plot "Total Activity generated by Leads Created on Day X".
                grouped[dateKey].calls += (s.callsOutgoing || 0);
                grouped[dateKey].whats += (s.whatsappAnswered || 0);
            }
        });
        return Object.values(grouped).sort((a, b) => a.date.localeCompare(b.date));
    }, [filteredSales]);

    // 2. Activity by Commercial
    const commercialData = useMemo(() => {
        const grouped: Record<string, any> = {};
        filteredSales.forEach(s => {
            const name = s.commercial || 'N/A';
            if (!grouped[name]) grouped[name] = { name, calls: 0, whats: 0, failed: 0 };
            grouped[name].calls += (s.callsOutgoing || 0);
            grouped[name].whats += (s.whatsappAnswered || 0);
            grouped[name].failed += (s.callsIncomingFailed || 0);
        });
        return Object.values(grouped).sort((a, b) => (b.calls + b.whats) - (a.calls + a.whats));
    }, [filteredSales]);

    return (
        <div className="space-y-6 pb-12">
            <h2 className="text-2xl font-bold text-white mb-4">Actividad Comercial</h2>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-96">
                {/* Evolution */}
                <div className="glass-panel p-6 flex flex-col">
                    <h3 className="text-lg font-bold text-gray-300 mb-2">Volumen de Actividad (por fecha de registro)</h3>
                    <p className="text-xs text-gray-500 mb-4">Muestra la suma de llamadas/wa de los leads registrados cada día.</p>
                    <div className="flex-1 min-h-0">
                        <ResponsiveContainer width="100%" height="100%">
                            <LineChart data={evolutionData}>
                                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                                <XAxis
                                    dataKey="date"
                                    stroke="#94a3b8"
                                    tickFormatter={(str) => format(new Date(str), 'dd MMM', { locale: es })}
                                    fontSize={12}
                                />
                                <YAxis stroke="#94a3b8" fontSize={12} />
                                <Tooltip contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155' }} />
                                <Legend />
                                <Line type="monotone" dataKey="calls" name="Llamadas" stroke="#38bdf8" strokeWidth={2} dot={false} />
                                <Line type="monotone" dataKey="whats" name="WhatsApp" stroke="#22c55e" strokeWidth={2} dot={false} />
                            </LineChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* Bar Stacked by Commercial */}
                <div className="glass-panel p-6 flex flex-col">
                    <h3 className="text-lg font-bold text-gray-300 mb-4">Mix de Actividad por Comercial</h3>
                    <div className="flex-1 min-h-0">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={commercialData} margin={{ top: 20 }}>
                                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                                <XAxis dataKey="name" stroke="#94a3b8" fontSize={12} />
                                <YAxis stroke="#94a3b8" fontSize={12} />
                                <Tooltip contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155' }} />
                                <Legend />
                                <Bar dataKey="calls" name="Llamadas" stackId="a" fill="#38bdf8" />
                                <Bar dataKey="failed" name="Fallidas" stackId="a" fill="#ef4444" />
                                <Bar dataKey="whats" name="WhatsApp" stackId="a" fill="#22c55e" />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>
        </div>
    );
};
